version: "3"
services:
  site:
    restart: always
    image: vc-tutorial-site
    environment:
      CONFIG_PATH: /var/www/static/config
      DJANGO_DEBUG: ${DEBUG}
      APP_SCRIPT: ${APP_SCRIPT}
      STI_SCRIPTS_PATH: ${STI_SCRIPTS_PATH}
    volumes:
      - ../app:/opt/app-root/src
      - ./site/config:/var/www/static/config
      - ui-artifacts:/var/dev/static/ui
    ports:
      - 8000:8080
    networks:
      - dts-vc-tutorial
    command: >
      /bin/bash -c "
      if [ $DEBUG ] && [ "$DEBUG" == "True" ]; then
      echo Running in debug mode;
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8080;
      else
        echo Running s2i container...;
        env;
        ${STI_SCRIPTS_PATH}/run;
      fi"
  
  ui-dev:
    image: node:fermium
    working_dir: /app
    volumes:
      - ../ui:/app
      - ui-artifacts:/app/dist
    ports:
      - 8081:8080
    networks:
      - dts-vc-tutorial
    command: npm run serve
  
  agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0
    environment:
      - ACAPY_LABEL=${AGENT_NAME}
      - ACAPY_ENDPOINT=${AGENT_ENDPOINT}
      - ACAPY_GENESIS_URL=${LEDGER_URL}/genesis
      - ACAPY_WALLET_NAME=${AGENT_WALLET_NAME}
      - ACAPY_WALLET_TYPE=indy
      - ACAPY_WALLET_KEY=${AGENT_WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_SEED=${AGENT_WALLET_SEED}
      - ACAPY_WEBHOOK_URL=${AGENT_WEBHOOK_URL}
      - ACAPY_LOG_LEVEL=${AGENT_LOG_LEVEL}
      - ACAPY_AUTO_PROVISION=true
      - ACAPY_AUTO_ACCEPT_INVITES=true
      - ACAPY_AUTO_ACCEPT_REQUESTS=true
      - ACAPY_AUTO_PING_CONNECTION=true
      - ACAPY_AUTO_RESPOND_MESSAGES=true
      - ACAPY_AUTO_RESPOND_CREDENTIAL_OFFER=true
      - ACAPY_AUTO_RESPOND_PRESENTATION_REQUEST=true
      - ACAPY_AUTO_RESPOND_CREDENTIAL_REQUEST=true
      - ACAPY_AUTO_VERIFY_PRESENTATION=true
    networks:
      - dts-vc-tutorial
    ports:
      - ${AGENT_HTTP_IN_PORT}:${AGENT_HTTP_IN_PORT}
      - ${AGENT_WS_IN_PORT}:${AGENT_WS_IN_PORT}
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
    volumes:
      - agent-wallet:/home/indy/.indy_client/wallet
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${AGENT_WALLET_SEED}\", \"role\":\"\", \"alias\":\"${AGENT_WALLET_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_IN_PORT} \
        --inbound-transport ws '0.0.0.0' ${AGENT_WS_IN_PORT} \
        --outbound-transport ws \
        --outbound-transport http \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${AGENT_ADMIN_MODE}",
      ]

networks:
  dts-vc-tutorial: 

volumes:
  ui-artifacts:
  agent-wallet: